version: '3'
services:

#  db:
#    restart: always
#    image: postgres:9.6-alpine
### Uncomment to enable DB persistance
#    volumes:
#      - ./data/pgsql:/var/lib/postgresql/data

#  redis:
#    restart: always
#    image: redis:4.0-alpine
### Uncomment to enable REDIS persistance
#    volumes:
#      - ./data/redis:/data

  web:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    environment:
      - WEB_CONCURRENCY=6
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "127.0.0.1:3000:3000"
#    depends_on:
#      - db
#      - redis
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    ports:
      - "127.0.0.1:4000:4000"
#    depends_on:
#      - db
#      - redis

  sidekiq:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    environment:
      - DB_POOL=20
    command: bundle exec sidekiq -c 20 -q default -q mailers -q pull -q push
#    depends_on:
#      - db
#      - redis
    volumes:
      - ./public/system:/mastodon/public/system
